### ISSUE TITLE
compile error when building for Web (The integer literal 0xF000FFFFFFFFFFFF can't be represented exactly in JavaScript)

### ISSUE THREAD

**Issue by RabbitMountain1** [getbraincloud/braincloud-dart#5]
first really cool to see brainClound coming to Dart.

when trying to use the package for the web we run into a compiler error =>

/D:/Data/Flutter/Pubcache/git/braincloud-dart-9ecb1d3fe5e8a207561a1b23dfd00a28cd3e1ca7/lib/src/internal/relay_comms.dart:590:41: Error: The integer literal 0xF000FFFFFFFFFFFF can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 0xf001000000000000 is the nearest value that can be represented exactly.
    int ackIdWithoutPacketId = (ackId & 0xF000FFFFFFFFFFFF).toUnsigned(64);

![image](https://github.com/user-attachments/assets/76893e23-a8e6-43a8-a3dc-56428e705d4b)

**Comment by marioc-bitheads** [comment]
Hi RabbitMountain1, 

Are you looking to use the Relay Server feature of Braincloud for your web app?

**Comment by RabbitMountain1** [comment]
Not at this stage, we would like to use the RTT feature (not sure if that is requied as underlying tech)

FYI: In a test if we change 0xF000FFFFFFFFFFFF to the Javascript safe max of 0xf001000000000000 we can compile the sdk for Web.
Most regular features seemed to work fine. We only ran into some issues related to RTT in which we couldn't disable it after it being enabled. If this issue is validated on our end we'll report it seperatly.

**Comment by marioc-bitheads** [comment]
Hi,

At this time, the Relay service will not be supported on the Web. I've added logic to let you build for the Web without that issue.
And note that there were some fixes applied to RTT lately, so you may want to try again.

Also, keep in mind that this is still not officially released code, so there is the potential for breaking changes.

Thanks again for letting us know about this.

**Comment by RabbitMountain1** [comment]
Confirmed the client now builds for Web without any errors. Thanks!

We can close this one, we'll report any new issues if/when they come up.
